# Generated by Django 3.0.3 on 2020-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The programming language a book covers', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='categrory',
            field=models.ManyToManyField(help_text='Choose a programming language this book covers', related_name='category', to='core.Category'),
        ),
    ]
