# Generated by Django 3.0.3 on 2020-02-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200228_1309'),
        ('core', '0002_book_created_at'),
    ]

    operations = [
    ]
