# Generated by Django 3.0.3 on 2020-02-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
